name: Deploy to Yandex Cloud

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install yc
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          echo "$HOME/yandex-cloud/bin" >> $GITHUB_PATH
      
      - name: Configure yc
        run: |
          echo '${{ secrets.YC_SA_JSON_CREDENTIALS }}' > /tmp/key.json
          yc config set service-account-key /tmp/key.json
          yc config set folder-id b1gsraf10hgd6naabfhg
      
      - name: Build and push
        run: |
          docker build -t cr.yandex/crpnjodd6609b4b1kg2d/barber-api:${{ github.sha }} .
          docker push cr.yandex/crpnjodd6609b4b1kg2d/barber-api:${{ github.sha }}
      
      - name: Deploy
        run: |
          yc serverless container revision deploy \
            --container-name barber-api \
            --image cr.yandex/crpnjodd6609b4b1kg2d/barber-api:${{ github.sha }} \
            --memory 128M \
            --service-account-id ajefln1mva94iejdnf1o
